# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opco', models.CharField(max_length=15)),
                ('app', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='build_archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='build_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_url', models.CharField(max_length=1000)),
                ('build_no', models.IntegerField(default=-1)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(default='default', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('right', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('ignore', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='environment_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=20)),
                ('app_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.application_list')),
            ],
        ),
        migrations.CreateModel(
            name='exec_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.count')),
                ('env_opco_app', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.environment_list')),
            ],
        ),
        migrations.CreateModel(
            name='fitnesse_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.build_detail')),
            ],
        ),
        migrations.CreateModel(
            name='latest_build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=15)),
                ('last_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_build', to='dashboard.build_archive')),
                ('last_successful_build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_successful_build', to='dashboard.build_archive')),
            ],
        ),
        migrations.CreateModel(
            name='test_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_name', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.application_list')),
            ],
        ),
        migrations.CreateModel(
            name='test_run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(default='No Execution Detail', max_length=5000000)),
                ('status', models.CharField(max_length=15)),
                ('duration', models.FloatField(default=0.0)),
                ('test_cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.test_case')),
            ],
        ),
        migrations.AddField(
            model_name='fitnesse_report',
            name='test_run',
            field=models.ManyToManyField(to='dashboard.test_run'),
        ),
        migrations.AddField(
            model_name='build_archive',
            name='build_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.build_detail'),
        ),
        migrations.AddField(
            model_name='build_archive',
            name='exec_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.exec_count'),
        ),
    ]
