# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('env_opco_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.environment_list')),
            ],
        ),
    ]
