# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_application_hosts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='application_hosts',
            new_name='application_host',
        ),
    ]
