# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170220_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='pipeline_opco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=15)),
                ('pipeline_url', models.CharField(max_length=50)),
                ('opco', models.CharField(max_length=15)),
                ('current_env', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='test_job_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_job_name', models.CharField(max_length=15)),
                ('test_job_url', models.CharField(max_length=50)),
                ('app', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='pipeline_opco',
            name='test_job_app',
            field=models.ManyToManyField(to='dashboard.test_job_app'),
        ),
    ]
