# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170301_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_opco',
            name='pipeline_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='test_job_app',
            name='test_job_url',
            field=models.CharField(max_length=1000),
        ),
    ]
