# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170301_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_opco',
            name='pipeline_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test_job_app',
            name='test_job_name',
            field=models.CharField(max_length=50),
        ),
    ]
