# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170301_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_opco',
            name='current_env',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
